version: 2

sources:
  - name: raw_data
    database: "{{ target.project }}"
    schema: raw                        
    tables:
      - name: customers_raw
      - name: orders_raw
      - name: products_raw
      - name: productvariants_raw